const pau = require("./index.js")
/*keep-line*/ const sampleCode = require("fs").readFileSync("sample.pau", "utf8")
const program = new pau(sampleCode)
const errors = program.getAllErrors()
console.log("Sample program compiled with " + errors.length + " errors.")
if (errors.length)
 console.log(errors.map(error => error.getMessage()))